[package]
name = "annex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.10.12"
font8x8 = { version = "0.3.1", default-features = false, features = [
    "unicode",
] }

[package.metadata.bootloader]
#minimum-framebuffer-height = 500
minimum-framebuffer-width = 800
