[package]
name = "annex"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bootloader = "0.10.12"
conquer-once = { version = "0.3.2", default-features = false }
font8x8 = { version = "0.3.1", default-features = false, features = [
    "unicode",
] }
spin = { version = "0.9.3", features = ["spin_mutex"], default-features = false }

[package.metadata.bootloader]
#minimum-framebuffer-height = 500
minimum-framebuffer-width = 800
