
[build]
target = "x86_64-annex.json"

[target.'cfg(target_os = "none")']
runner = "just runner"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]
